services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    container_name: bravest-backend
    ports:
      - "8080:8080"
    networks:
      - bravest-net
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
      - .env
    container_name: bravest-db
    ports:
      - "3306:3306"
    networks:
      - bravest-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

networks:
  bravest-net:
    driver: bridge
