services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    container_name: bravest-backend
    ports:
      - "8080:8080"
    networks:
      - bravest-net
    depends_on:
      db:
        condition: service_healthy
      keystore:
        condition: service_started

  db:
    image: mysql:8.0
    env_file:
      - .env
    container_name: bravest-db
    ports:
      - "3306:3306"
    networks:
      - bravest-net
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpw" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  keystore:
    image: valkey/valkey:9.0.0
    container_name: bravest-keystore
    ports:
      - "6379:6379"
    networks:
      - bravest-net

networks:
  bravest-net:
    driver: bridge
